# Generated by Django 2.0.5 on 2018-05-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('cateid', models.AutoField(primary_key=True, serialize=False)),
                ('catename', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('memberid', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('memberaccount', models.CharField(blank=True, max_length=40, null=True)),
                ('memberpas', models.CharField(blank=True, max_length=40, null=True)),
                ('membername', models.CharField(blank=True, max_length=20, null=True)),
                ('memberphone', models.IntegerField(blank=True, null=True)),
                ('memberaddres', models.CharField(blank=True, max_length=255, null=True)),
                ('memberkey', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('proname', models.CharField(blank=True, max_length=20, null=True)),
                ('proprice', models.IntegerField(blank=True, null=True)),
                ('procont', models.CharField(blank=True, max_length=255, null=True)),
                ('pronum', models.IntegerField(blank=True, null=True)),
                ('proimg', models.CharField(blank=True, max_length=255, null=True)),
                ('proid', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('procate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Cate')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('memberid', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('selectproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessOrder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('memberid', models.CharField(blank=True, max_length=45)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('selectproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product')),
            ],
        ),
        migrations.AddField(
            model_name='leavemessage',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.SuccessOrder'),
        ),
        migrations.AddField(
            model_name='leavemessage',
            name='selectproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product'),
        ),
    ]
