# Generated by Django 2.0.5 on 2018-05-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate',
            name='catename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
