# Generated by Django 2.0.5 on 2018-05-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='contant',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
    ]
