# Generated by Django 2.0.5 on 2018-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_leavemessage_contant'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='ifbuy',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
