# Generated by Django 2.0.5 on 2018-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_leavemessage_ifbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='ifbuy',
            field=models.BooleanField(default=1),
        ),
    ]
