# Generated by Django 2.0.5 on 2018-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180515_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='ifbuy',
            field=models.BooleanField(),
        ),
    ]
